//采集接口
    var vod_url_list = {
        "无尽资源": "https://api.wujinapi.com/api.php",
        "快播云": "http://www.kuaibozy.com/api.php",
        "天空云": "https://api.tiankongapi.com/api.php",
        "百度资源": "https://api.apibdzy.com/api.php",
        "爱播资源": "https://cj.apiabzy.com/api.php",
        "葡萄资源": "https://caiji.putaozy.net/inc/apijson_vod.php",
        "523资源": "https://caiji.523zyw.com/inc/apijson_vod.php",
        "芒果资源": "https://mgzyz1.com/api.php/provide/vod/",
        "乐鱼资源": "https://www.leyuzyapi.com/inc/apijson_vod.php",
        "水蜜桃": "http://51smt4.xyz/api.php/provide/vod/",
        "秀色资源": "https://api.xiuseapi.com/api.php/provide/vod/",
        "探探资源": "https://apittzy.com/api.php/provide/vod/",
        "*色猫资源": "https://api.maozyapi.com/inc/apijson_vod.php",
        "*草莓资源": "https://caiji.caomeiapi.com/inc/apijson_vod.php",
        "*爱看资源": "http://www.aikanzyz9.com/inc/apijson_vod.php",
        "*花魁资源": "https://caiji.huakuiapi.com/inc/apijson_vod.php",
        "*色窝资源": "https://sewozyapi.com/api.php/provide/vod/",
        "*淫窝资源": "https://api.yinwoapi.com/api.php/provide/vod/",
        "*4000资源": "https://www.4000zy.com/inc/apijson_vod.php",
        "*大雕资源": "http://www.caobi209.vip/api.php/provide/vod/",
        "*色屌丝资源": "http://sdszyapi.com/home/cjapi/asbb/mc10/vod/xml",
        "*小姐姐资源": "https://xjjzyapi.com/home/cjapi/askl/mc10/vod/xml",
        "*52AVAV": "https://52zyapi.com/home/cjapi/asda/mc10/vod/xml",
        "*水帘洞资源": "https://www.sldcaiji.com/home/cjapi/s6da/mc10/vod/json",
        "*我要啪啪": "http://www.caiji21.com/home/cjapi/klkl/mc10/vod/xml",
        "*AV集中淫": "https://www.caiji22.com/home/cjapi/klp0/mc10/vod/xml",
        "*夜夜撸资源": "https://www.caiji23.com/home/cjapi/kls6/mc10/vod/xml",
        "*大屌丝资源": "http://www.caiji24.com/home/cjapi/p0d2/mc10/vod/xml",
        "*咪咪资源": "http://www.caiji25.com/home/cjapi/p0as/mc10/vod/xml",
        "*鲍鱼AV": "http://caiji26.com/home/cjapi/p0g8/mc10/vod/xml",
        "*精工厂资源": "https://jgczyapi.com/home/cjapi/kld2/mc10/vod/xml",
        "*点点娱乐": "https://xx55zyapi.com/home/cjapi/ascf/mc10/vod/xml",
        "*淫人妻资源": "http://www.yrqcaiji.com/home/cjapi/s6c7/mc10/vod/json",
        "*小处女资源": "http://xcncaiji.com/home/cjapi/s6bb/mc10/vod/json",
        "*大MM资源": "https://www.dmmapi.com/home/cjapi/asd2c7/mc10/vod/xml",
        "*黄瓜TV资源": "https://www.caiji10.com/home/cjapi/cfs6/mc10/vod/xml",
        "*快播盒子资源": "https://www.caiji09.com/home/cjapi/cfp0/mc10/vod/xml",
        "*大香蕉资源": "https://www.caiji08.com/home/cjapi/cfkl/mc10/vod/xml",
        "*日本AV在线": "https://www.caiji07.com/home/cjapi/cfcf/mc10/vod/xml",
        "*久久热在线": "https://www.caiji06.com/home/cjapi/cfbb/mc10/vod/xml",
        "*青青草视频": "https://www.caiji05.com/home/cjapi/cfda/mc10/vod/xml",
        "*麻豆视频": "https://www.caiji04.com/home/cjapi/cfc7/mc10/vod/xml",
        "*一本道资源": "https://www.caiji03.com/home/cjapi/cfg8/mc10/vod/xml",
        "*草榴视频": "https://www.caiji02.com/home/cjapi/cfas/mc10/vod/xml",
        "*亚洲成人在线": "https://www.caiji01.com/home/cjapi/cfd2/mc10/vod/xml",
        "*天噜啦资源": "http://www.987caiji.com/api/max.php",
        "*99资源": "http://99zy.pw/api.php/provide/vod/",
        "*010爱资源": "http://www.010aizy.com/API/macs.php",
        "*痴汉队长": "https://javcaptain.com/api.php/provide/vod/",
        "*抖阴视频": "https://www.888dav.com/api.php/provide/vod/",
        "*麻豆视频2": "https://madouse.la/api.php/provide/vod/",
        "*91麻豆": "https://91md.me/api.php/provide/vod/",
        "*99资源吧": "http://99zyba.com/api.php/provide/vod/",
        "*爱操资源": "https://aicaozy.com/api.php/provide/vod/",
        "*浪潮资源": "http://langchaozy6.com/api.php/provide/vod/",
        "*速播资源": "https://api.suboapi.com/api.php/provide/vod/",
        "*酷豆资源": "https://kudouzy.com/api.php/provide/vod/",
        "*酷豆2": "https://api.kdapi.info/api.php/provide/vod/",
        "*酷伦理": "https://api.kudian70.com/api.php/provide/vod/",
        "*影库资源": "https://api.ykapi.net/api.php/provide/vod/",
        "*万影色": "https://wanying4.com/api.php/provide/vod/",
        "*银龙资源": "https://yinlong.tv/api.php/provide/vod/",
        "*奶茶资源": "https://caiji.naichaapi.com/inc/apijson_vod.php",
        "*爱播资源": "https://cj.apiabzy.com/api.php/provide/vod/",
        "*美少女资源": "https://www.msnii.com/api/xml.php",
        "*淫水机资源": "https://www.xrbsp.com/api/xml.php",
        "*香奶儿资源": "https://www.gdlsp.com/api/xml.php",
        "*白嫖资源": "https://www.kxgav.com/api/xml.php",
        "*小湿妹资源": "https://www.afasu.com/api/xml.php",
        "*黄AV资源": "https://www.pgxdy.com/api/json.php",
        "*大地资源": "https://dadiapi.com/api.php",
        "*CK资源": "http://www.feifei67.com/api.php/provide/vod/",
        "*老鸭资源": "https://api.apilyzy.com/api.php/provide/vod/",
        "*花椒资源": "https://apihjzy.com/api.php/provide/vod/",
        "*辣椒资源": "https://apilj.com/api.php/provide/vod/at/json/",
        "*乐播资源": "https://lbapi9.com/api.php/provide/vod/",
        "*博天堂": "http://bttcj.com/inc/sapi.php",
        "*环亚资源": "http://wmcj8.com/inc/sapi.php",
        "*JAV名优馆": "http://mygzycj.com/api.php?ac=videolist",
        "*AVZY6888资源": "http://m.7777688.com/inc/apijson.php",
        "*色色资源": "http://secj8.com/inc/sapi.php?ac=videolist",
        "*玖玖资源": "http://99zywcj.com/inc/sapi.php?ac=videolist",
        "*久草资源": "http://jcspcj8.com/api?ac=videolist",
        "*狼少年": "http://cjmygzy.com/inc/sapi.php?ac=videolist",
        "*富二代资源": "http://f2dcj6.com/sapi?ac=videolist",
        "*字幕网": "http://zmcj88.com/sapi?ac=videolist",
        "*利来资源": "http://llzxcj.com/inc/sck.php?ac=videolist",
        "*佳丽资源": "http://www.jializyzapi.com/api.php/provide/vod/",
        "*番号资源": "http://fhapi9.com/api.php/provide/vod/",
        "*鲨鱼资源": "https://shayuapi.com/api.php/provide/vod/",
        "*速度资源": "http://www.ggmmzy.com:9999/inc/xml",
        "*KK写真资源": "https://kkzy.me/api.php/provide/vod/",
    }

//播放解析接口
var play_url_list={
    "百度资源":"https://jx.jxbdzyw.com/m3u8/?url=",
    "解析2":"https://jx.7kjx.com/?url="
}

//代理请求接口
var proxyurl = "https://apibf.herokuapp.com"; 

//过滤排除加载类型
var ex = ["资讯", "公告", "头条", "伦理片", "邵氏电影","三级片","体育赛事","伦理","论理","倫理","福利","激情","理论","写真","情色","美女","街拍","赤足","性感","里番","VIP"];

//首页顶部导航条显示
var ntn = ["电影", "连续剧", "综艺", "动漫"];

